# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='человекопонятный url-адрес'),
        ),
    ]
