# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', max_length=64, verbose_name='человекочитаемый адрес'),
            preserve_default=False,
        ),
    ]
