# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170607_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='человекопонятный url-адрес'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'parent'), ('slug', 'parent')]),
        ),
    ]
