# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170607_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='store/products/%Y/%m/%d/'),
        ),
    ]
