# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
