# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20170608_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=64, verbose_name='человекопонятный url-адрес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=64, unique=True, verbose_name='человекопонятный url-адрес'),
        ),
    ]
